vich_uploader:
    db_driver: orm

    mappings:
        images_post:
            uri_prefix: /images/post
            upload_destination: '%kernel.project_dir%/public/images/post'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
